name: electron-react-boilerplate
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Build the app
        run: yarn deploy
